name: CD

on:
  push:
    branches:
      - main

enable-openid-connect: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Login to registry
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.REGISTRY_HOSTNAME }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Create Forgejo JWT
        id: jwt
        run: |
          jwt=$( \
            curl --fail \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${{ vars.OIDC_AUDIENCE }}" \
            | jq -r ".value" \
          )
          echo "::add-mask::$jwt"
          echo "jwt=$jwt" >> $FORGEJO_OUTPUT

      - name: Login to Forgejo
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.GIT_HOSTNAME }}
          username: ${{ forgejo.actor }}
          password: ${{ steps.jwt.outputs.jwt }}

      - name: Build & push images
        env:
          REGISTRY_HOSTNAME: ${{ vars.REGISTRY_HOSTNAME }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          GIT_HOSTNAME: ${{ vars.GIT_HOSTNAME }}
          GIT_OWNER: ${{ vars.GIT_OWNER }}
        run: ./scripts/build.sh --push
