name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY_HOSTNAME: ${{ vars.REGISTRY_HOSTNAME }}
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      GIT_HOSTNAME: ${{ vars.GIT_HOSTNAME }}
      GIT_OWNER: ${{ vars.GIT_OWNER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install cosign
        uses: https://github.com/sigstore/cosign-installer@v4.1.2

      - name: Build & push images
        run: ./scripts/build.sh --push
