name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Login to registry
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.REGISTRY_HOSTNAME }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Install cosign
        uses: https://github.com/sigstore/cosign-installer@v4.1.2

      - name: Build & push images
        env:
          REGISTRY_HOSTNAME: ${{ vars.REGISTRY_HOSTNAME }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          GIT_HOSTNAME: ${{ vars.GIT_HOSTNAME }}
          GIT_OWNER: ${{ vars.GIT_OWNER }}
        run: ./scripts/build.sh --push
