FROM docker://docker.io/node@sha256:934240a162082fd8b8a2f90cd5114446443f1eba1c5378f6687167ca405e6584 AS base

LABEL org.opencontainers.image.created="${IMAGE_CREATED}" \
      org.opencontainers.image.authors="Konrad Guzek" \
      org.opencontainers.image.url="https://registry.guzek.uk/harbor/projects/5/repositories/node-debian" \
      org.opencontainers.image.documentation="https://git.guzek.uk/kguzek/runner-images/src/branch/main/README.md" \
      org.opencontainers.image.source="https://github.com/kguzek/runner-images" \
      org.opencontainers.image.version="${IMAGE_VERSION}" \
      org.opencontainers.image.revision="${IMAGE_REVISION}" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.title="A generic runner OCI image for use by Forgejo Actions" \
      org.opencontainers.image.description="Built to balance compatibility with GitHub Actions' `ubuntu-latest` against low image size. Based on Debian and comes with Node.js to support actions like [actions/checkout](https://git.guzek.uk/actions/checkout) which rely on it."

RUN apt-get update && \
  # used for e.g. Cosign: https://git.guzek.uk/kguzek/liveseries-server/actions/runs/3/jobs/0/attempt/1
  apt-get install -y gettext-base
